<div class="box_bottom">
  <div class="header"><img src="/img/bottom_text_arenas_guide.jpg" alt="Info" /></div>
  <img src="/img/bottom_image_globus.jpg" alt="Info" class="toleft" />
  <?php echo get_static_text(12); ?>
</div>

<div class="box_bottom">
  <div class="header"><img src="/img/bottom_text_webmasters.jpg" alt="Info" /></div>
  <img src="/img/bottom_image_stats.jpg" alt="Info" class="toleft" />
  <?php echo get_static_text(13); ?>
</div>

<div class="box_bottom">
  <div class="header"><img src="/img/bottom_text_database.jpg" alt="Info" /></div>
  
  <img src="/img/bottom_image_questions.jpg" alt="Info" class="toleft" />
  <?php echo get_static_text(14); ?>
</div>

<div class="clear">&nbsp;</div>
