&copy; Copyright <?php echo date("Y");?> European Ice Hockey Online AB &amp; <a href="http://www.eSports.cz" onclick="return !window.open(this.href);" class="out">eSports.cz s.r.o.</a> | <a href="mailto:info@eurohockey.com">info@eurohockey.com</a><br />
<a href="http://www.nalede.cz/hokejova-vystroj">Hokejová výstroj</a>

<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js#xfbml=1" type="text/javascript"></script>
<script type="text/javascript">
  window.fbAsyncInit = function() {
    FB.init({appId: '106902132746411', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/en_US/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7396775-32']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


<a href="http://www.toplist.cz/stat/1024986"><script language="JavaScript" type="text/javascript">
<!--
document.write('<img src="http://toplist.cz/dot.asp?id=1024986&amp;http='+escape(document.referrer)+'&amp;t='+escape(document.title)+
'" width="1" height="1" border=0 alt="TOPlist" />');
//--></script></a><noscript><img src="http://toplist.cz/dot.asp?id=1024986" border="0"
alt="TOPlist" width="1" height="1" /></noscript>
