        <div class="header_cufon"><span class="header_text">Leagues</span></div>
        <div class="box countries_leagues">
            
            <p>
            <?php echo get_flag(strtolower('cze'),15,11);?>
              <strong>Czech Rep.:&nbsp;</strong> 
              <span><a href="/league/130-extraliga-cze.html" title="Tipsport extraliga">Tipsport extraliga</a> | </span>
              <span><a href="/league/199-1liga-cze.html" title="1.liga">1.liga</a> | </span>
              <span><a href="/league/208-2liga-cze.html" title="2.liga">2.liga</a></span>
            </p>
            
            <p>
            <?php echo get_flag(strtolower('fin'),15,11);?>
              <strong>Finland:&nbsp;</strong> 
              <span><a href="/league/128-sm-liiga.html" title="SM-Liiga">SM-Liiga</a> | </span>
              <span><a href="/league/369-mestis.html" title="Mestis">Mestis</a></span>
            </p>
            
            <p>
            <?php echo get_flag(strtolower('ger'),15,11);?>
              <strong>Germany:&nbsp;</strong> 
              <span><a href="/league/129-del.html" title="DEL">DEL</a> | </span>
              <span><a href="/league/145-2-bundesliga.html" title="2.Bundesliga">2.Bundesliga</a></span>
            </p>
            
            <p>
            <?php echo get_flag(strtolower('rus'),15,11);?>
              <strong>Russia:&nbsp;</strong> 
              <span><a href="/league/395-khl.html" title="KHL">KHL</a> | </span>
              <span><a href="/league/188-vysshaya-liga-rus-2.html" title="Vysshaya liga">Vysshaya liga</a></span>
            </p>
            
            <p>
            <?php echo get_flag(strtolower('svk'),15,11);?>
              <strong>Slovakia:&nbsp;</strong> 
              <span><a href="/league/131-extraliga-svk.html" title="Tipsport Extraliga">Tipsport Extraliga</a> | </span>
              <span><a href="/league/200-1liga-svk.html" title="1.liga">1.liga</a></span>
            </p>
            
            <p>
            <?php echo get_flag(strtolower('swe'),15,11);?>
              <strong>Sweden:&nbsp;</strong> 
              <span><a href="/league/127-elitserien.html" title="Elitserien">Elitserien</a> | </span>
              <span><a href="/league/355-hockeyallsvenskan.html" title="Allsvenskan">Allsvenskan</a></span>
            </p>
            
            <p>
            <?php echo get_flag(strtolower('sui'),15,11);?>
              <strong>Switzerland:&nbsp;</strong> 
              <span><a href="/league/124-nationalliga-a.html" title="NLA">NLA</a> | </span>
              <span><a href="/league/125-nationalliga-b.html" title="NLB">NLB</a></span>
            </p>
            
            <p>
              <strong>Other:&nbsp;</strong> 
              <span><a href="/league/421-nhl.html" title="NHL">NHL</a> | </span>
              <span><a href="/league/415-ahl.html" title="AHL">AHL</a> | </span>
              <span><a href="/league/133-ebel.html" title="EBEL">EBEL</a> | </span>
              <span><a href="/league/136-serie-a.html" title="Serie A (ITA)">Serie&nbsp;A&nbsp;(ITA)</a> | </span>
              <span><a href="/league/134-ligue-magnus.html" title="Magnus (FRA)">Magnus&nbsp;(FRA)</a> | </span>
              <span><a href="/league/137-get-ligaen.html" title="GET (NOR)">GET&nbsp;(NOR)</a> | </span>
              <span><a href="/league/144-al-bank-ligaen.html" title="AL-B (DEN)">AL-B&nbsp;(DEN)</a> | </span>
              <span><a href="/league/150-belarus-open-league.html" title="Belarus">Belarus</a></span>
            </p>
            
            <div class="link right"><a href="/leagues.html" title="More league pages">More league pages&raquo;</a></div>
          
         </div>     