      <div id="box_search">
          <form action="/players.html">
		        <div>
		          <input type="text" name="player_search" id="search_input" value="Type in player name" onclick="this.form.player_search.value='';" />
        		  <input type="submit" id="search_submit" value="" />
        		  <input type="hidden" name="write_player_search" value="1" />
        		  <div class="clear">&nbsp;</div>
        		  <a href="/players.html?advanced=1" title="Advanced player search">Advanced player search</a>
	         </div>
		      </form>
         </div>