        <div id="ads_index_middle"><?php show_ads("ads_index_middle"); ?></div>
        
        <div class="text_col_left">
            
            <div class="header tournaments"><span>Tournaments</span></div>
            <div class="box tournaments">
              <?php echo get_static_text(15); ?>
            </div>
             
          </div>
          
          <div class="text_col_right">
            
            <div class="header fan_forums"><span>Fan forums</span></div>
            <div class="box fan_forums">
              
              <p class="header">Forums are great</p>
              <p>
                 <img src="/img/ico/ico_forum.jpg" alt="Forum" height="37" width="41" class="toleft" />
                 Discuss your favourite team or player with other fans on one of our discussion boards! 
              </p>
              <p class="line">&nbsp;</p>
              <p class="bold center"><span><a href="fan-forum.html" title="Join the forum">Join the forum!</a></span></p>
              
            </div>
            
          </div>
          <div class="clear">&nbsp;</div>